ok. I cleaned up. the -reportWebVitals.js- is still a question how to…
mBraun1970/reactApp pull request #4
Opened 2023-12-05 15:11 UTC by mBraun1970

… get it in the no need folder without error .....

2023-12-05 15:41 UTC, F-Kirchhoff requested changes
This looks great already! Please have a look, I found some minor issues with your html elements.

2023-12-05 15:41 UTC, F-Kirchhoff commented on src/AlbumCard/AlbumCard.css
> +  height: 50vh;
please don't use vh and vw here, you can use width: 100% and "aspect-ratio: 1 / 2"

2023-12-05 15:41 UTC, F-Kirchhoff commented on src/AlbumCard/AlbumCard.js
> +    </section>
very nice semantic html!

2023-12-05 15:41 UTC, F-Kirchhoff commented on src/AlbumCard/AlbumCard.js
> +    // this is the solution , let me get there :) check from line 18
What do you mean by this comment?

2023-12-05 15:41 UTC, F-Kirchhoff commented on src/AlbumCard/AlbumCard.js
> +    // </div>
please remove any comments like this before merging.

2023-12-05 15:41 UTC, F-Kirchhoff commented on src/App.css
> +  /* justify-content: center; */
please remove those comments as well.

2023-12-05 15:41 UTC, F-Kirchhoff commented on src/App.js
> +        the AlbumCards
Please remove this text.

2023-12-05 15:41 UTC, F-Kirchhoff commented on src/App.js
> +        <article className="album-list">
your album list should be a "ul"

2023-12-05 15:41 UTC, F-Kirchhoff commented on src/App.js
> +            <aside key={album.id}>
this should be a 'li'

2023-12-05 16:37 UTC, mBraun1970 commented on src/App.js
> +            <aside key={album.id}>
first you say nice semantic , now i get a change ... :) .... ok

2023-12-05 16:37 UTC, mBraun1970 commented on src/App.js
> +        <article className="album-list">
done

2023-12-05 16:37 UTC, mBraun1970 commented on src/AlbumCard/AlbumCard.js
> +    </section>
juhu :)

2023-12-05 16:37 UTC, mBraun1970 commented on src/AlbumCard/AlbumCard.js
> +    // this is the solution , let me get there :) check from line 18
this was a left over , its gone now

2023-12-05 16:51 UTC, F-Kirchhoff requested changes
you still need to change the html elements to ul and li.

2023-12-06 09:50 UTC, onemanwenttomow approved these changes
One element to change otherwise it looks good to me!

2023-12-06 09:50 UTC, onemanwenttomow commented on src/App.js
> +        <article className="albumList">
I think this should be a <ul> element.

2023-12-06 10:09 UTC, merged